# configuration
NAME = "msaouabS"
IP = "192.168.56.110"
BOX = "generic/alpine318"
MEMORY = 1024
CPUS = 1

Vagrant.configure("2") do |config|
	config.vm.define NAME do |s|
		s.vm.box = BOX
		s.vm.hostname = NAME
		s.vm.network "private_network", ip: IP
		s.vm.provider "virtualbox" do |vb|
			vb.name = NAME
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	s.vm.synced_folder "./confs", "/home/vagrant/confs"
	s.vm.provision "shell", path: "./tools/setup.sh"
	end
end