# configuration
S_NAME = "msaouabS"
S_IP = "192.168.56.110"
BOX = "generic/alpine318"
MEMORY = 1024
CPUS = 1

Vagrant.configure("2") do |config|
	config.vm.define S_NAME do |s|
		s.vm.box = BOX
		s.vm.hostname = S_NAME
		s.vm.network "private_network", ip: S_IP
		s.vm.provider "virtualbox" do |vb|
			vb.name = S_NAME
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	s.vm.provision "shell", path: "./tools/setup.sh"
	end
end