# server configuration
S_NAME = "msaouabS"
S_IP = "192.168.56.110"

#worker configuration
SW_NAME = "msaouabSW"
SW_IP = "192.168.56.111"

# common configuration
BOX = "generic/alpine318"
MEMORY = 1024
CPUS = 1

Vagrant.configure("2") do |config|
	config.vm.define S_NAME do |s|
		s.vm.box = BOX
		s.vm.hostname = S_NAME
		s.vm.network "private_network", ip: S_IP
		s.vm.provider "virtualbox" do |vb|
			vb.name = S_NAME
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	s.vm.provision "shell", path: "./tools/server.sh"
	end

	config.vm.define SW_NAME do |sw|
		sw.vm.box = BOX
		sw.vm.hostname = SW_NAME
		sw.vm.network "private_network", ip: SW_IP
		sw.vm.provider "virtualbox" do |vb|
			vb.name = SW_NAME
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	sw.vm.provision "file", source: ".vagrant/machines/msaouabS/virtualbox/private_key", destination: "/home/vagrant/private_key"
	sw.vm.provision "shell", path: "./tools/worker.sh"
	end
end
