#server
S_NAME = "msaouab"
S_IP = "192.168.41.41"

#server_worker
SW_NAME = "msaouab"
SW_IP = "192.168.41.42"

#common config
VAGRANT_BOX = "centos/7"
RAM = 1024
CPU = 1

Vagrant.configure("2") do |s|
	s.vm.box = VAGRANT_BOX
	s.vm.define S_NAME do |s1|
		s1.vm.hostname = S_NAME
		s1.vm.network "private_network", ip: S_IP
		s1.vm.provider "virtualbox" do |s2|
			s2.memory = RAM
			s2.cpus = CPU
		end
	end
end