#common configuration
BOX = "generic/alpine318"
MEMORY = "1024"
CPUS = 1

Vagrant.configure("2") do |config|
	config.vm.define "msaouabS" do |s|
		s.vm.box = BOX
		s.vm.hostname = "msaouabS"
		s.vm.network "private_network", ip: "192.168.56.110"
		s.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "msaouabS"]
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	config.vm.provision "shell", path: "./tools/server.sh"
	config.vm.synced_folder "./data", "/var/www"
	end

	config.vm.define "msaouabSW" do |sw|
		sw.vm.box = BOX
		sw.vm.hostname = "msaouabSW"
		sw.vm.network "private_network", ip: "192.168.56.111"
		sw.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", "msaouabSW"]
			vb.memory = MEMORY
			vb.cpus = CPUS
		end
	config.vm.provision "shell", path: "./tools/worker.sh"
	config.vm.synced_folder "./data", "/var/www"
	end
end